server:
  port: 8082
  tomcat:
    connection-timeout: 300000

elasticsearch-client:
    hosts: http://8.138.31.44:9200

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    name: datasource
    url: jdbc:mysql://8.138.31.44:3306/bilibili?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 8.138.31.44
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.bilibili: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

xxl:
  job:
    admin:
      addresses: http://8.138.31.44:9916/xxl-job-admin
    accessToken: default_token
    executor:
      port: 9910
      appname: demo-service-impl
      logpath: /data/applogs/xxl-job/jobhandler

knife4j:
    enable: true
    openapi:
        title: Bilibili-视频服务接口文档
        description: "Bilibili-搜索服务接口文档"
        email:
        concat:
        url: https://www.bilibili.com
        version: v1.0.0
        group:
            default:
                group-name: default
                api-rule: package
                api-rule-resources:
                    - com.bilibili.search.controller

